model_list:
  - model_name: nvidia/*
    litellm_params:
      model: openai/*
      api_key: os.environ/NVIDIA_API_KEY

  - model_name: gemini/*
    litellm_params:
      model: gemini/*
      api_key: os.environ/GEMINI_API_KEY

litellm_settings:
  drop_params: true
  set_verbose: true

server_settings:
  host: "0.0.0.0"
  port: 4000
